import os
from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional, Tuple
import json, re, time

import numpy as np
import pandas as pd
from dotenv import load_dotenv

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

from langchain_dartmouth.llms import DartmouthLLM, ChatDartmouth
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from langchain_core.runnables import RunnablePassthrough

from langchain_dartmouth.llms import ChatDartmouth
from dotenv import load_dotenv
import os

# Load variables from .env file
load_dotenv() 
# Get the key
api_key = os.getenv("DARTMOUTH_CHAT_API_KEY")


# llm_df = pd.read_csv("data/cleaned_merged_seasons.csv", low_memory=False)

@dataclass
class FeatureConfig:
    # Columns to drop before engineering features
    columns_to_drop: List[str] = field(default_factory=lambda: [
    "team_a_score","team_h_score","was_home","modified","round",
    "opponent_team","kickoff_time","fixture","position","team",
    "element","creativity","influence","threat","bonus",
    "transfers_in","transfers_out"
    ])
    # Rolling window (games) used to aggregate numeric stats by player
    rolling_window_games: int = 10
    # Target column to predict
    target_points_column: str = "total_points"
    # Column that uniquely identifies a player
    player_name_column: str = "name"
    # Gameweek column used for ordering within each player
    gameweek_column: str = "GW"
    # Which engineered features to keep and (optionally) send to the LLM
    # Leave empty to keep all numeric rolling features
    selected_feature_columns: List[str] = field(default_factory=list)

@dataclass
class LlmConfig:
    model_name: str = "meta.llama-3.2-11b-vision-instruct"
    temperature: float = 0.0
    max_output_tokens: int = 128
    # How many rows to score with the LLM (to control cost)
    max_rows_to_score: int = 10

def load_fantasy_data(
    merged_gw_path: str = "data/merged_gw.csv",
    merged_seasons_path: str = "data/cleaned_merged_seasons.csv"
    ) -> dict[str, pd.DataFrame]:
    data_frames: dict[str, pd.DataFrame] = {
    "merged_gw": pd.read_csv(merged_gw_path, on_bad_lines="skip", low_memory=False),
    "merged_seasons": pd.read_csv(merged_seasons_path, on_bad_lines="skip", low_memory=False),
    }
    return data_frames

def compute_player_rolling_totals(
    input_df: pd.DataFrame,
    feature_config: FeatureConfig
) -> pd.DataFrame:
    """
    Enhanced feature engineering for FPL predictions.
    Adds lag features, rolling averages, play indicators, etc.
    Maintains compatibility with the downstream pipeline.
    Fills NaNs generated by shifts/rolling with 0.
    """
    df = input_df.copy()

    # ----------------------------------------------------
    # 1. Drop irrelevant columns
    # ----------------------------------------------------
    df = df.drop(columns=feature_config.columns_to_drop, errors="ignore")

    # Ensure GW numeric for sorting
    gw_col = feature_config.gameweek_column
    df[gw_col] = pd.to_numeric(df[gw_col], errors="coerce")

    # Sort properly before rolling
    df = df.sort_values([feature_config.player_name_column, gw_col])

    # Identify numeric stats (excluding identifiers)
    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    for col in [gw_col, feature_config.target_points_column]:
        if col in numeric_cols:
            numeric_cols.remove(col)

    # ----------------------------------------------------
    # 2. Lag features
    # ----------------------------------------------------
    player_col = feature_config.player_name_column
    target_col = feature_config.target_points_column

    # Simple lag
    df["points_last_1"] = df.groupby(player_col)[target_col].shift(1)

    # Rolling means with reset_index to avoid MultiIndex issues
    for window in [3, 5]:
        col_name = f"points_last_{window}"
        df[col_name] = (
            df.groupby(player_col)[target_col]
            .rolling(window)
            .mean()
            .shift(1)
            .reset_index(level=0, drop=True)
        )

    # Minutes-based features (played / starter / rolling minutes)
    if "minutes" in df.columns:
        df["played_last_1"] = (df.groupby(player_col)["minutes"].shift(1) > 0).astype(int)
        df["starter_last_1"] = (df.groupby(player_col)["minutes"].shift(1) >= 60).astype(int)
        df["minutes_last_3"] = (
            df.groupby(player_col)["minutes"]
            .rolling(3)
            .mean()
            .shift(1)
            .reset_index(level=0, drop=True)
        )

    # ----------------------------------------------------
    # 3. Rolling means for all other numeric columns
    # ----------------------------------------------------
    window = feature_config.rolling_window_games
    for col in numeric_cols:
        new_col = f"{col}_mean_last_{window}"
        df[new_col] = (
            df.groupby(player_col)[col]
            .rolling(window)
            .mean()
            .shift(1)
            .reset_index(level=0, drop=True)
        )

    # ----------------------------------------------------
    # 4. Keep original target + identifiers
    # ----------------------------------------------------
    keep_cols = [
        player_col,
        gw_col,
        target_col,
    ]

    engineered_cols = [c for c in df.columns if c not in keep_cols]

    out_df = df[keep_cols + engineered_cols]

    # ----------------------------------------------------
    # 5. Fill any NaNs created by rolling/shift operations with 0
    # ----------------------------------------------------
    out_df = out_df.fillna(0)

    return out_df

def build_feature_matrix_and_target(
    engineered_df: pd.DataFrame,
    feature_config: FeatureConfig
) -> Tuple[pd.DataFrame, pd.Series, List[str]]:
    """
    Build the feature matrix X and target y for ML.
    Includes all numeric rolling/lag features unless specific features are selected.
    """
    target_series = engineered_df[feature_config.target_points_column]

    # Include all numeric columns except identifiers and target
    exclude_cols = {
        feature_config.player_name_column,
        feature_config.gameweek_column,
        feature_config.target_points_column
    }

    if feature_config.selected_feature_columns:
        # Only include features explicitly selected
        feature_columns = [c for c in feature_config.selected_feature_columns if c in engineered_df.columns]
    else:
        # Include all numeric engineered columns (rolling, lag, etc.)
        numeric_cols = engineered_df.select_dtypes(include=[np.number]).columns.tolist()
        feature_columns = [c for c in numeric_cols if c not in exclude_cols]

    feature_matrix = engineered_df[feature_columns].copy()
    return feature_matrix, target_series, feature_columns

# baseline Machine learning Linear Regression 
def evaluate_linear_regression_baseline(
    feature_matrix: pd.DataFrame,
    target_series: pd.Series,
    random_seed: int = 42
    ) -> float:
    """Train/test split and MAE for a simple Linear Regression baseline."""
    X_train, X_test, y_train, y_test = train_test_split(
    feature_matrix, target_series, test_size=0.2, random_state=random_seed
    )
    regression_model = LinearRegression()
    regression_model.fit(X_train, y_train)
    baseline_predictions = regression_model.predict(X_test)
    mae_value = mean_absolute_error(y_test, baseline_predictions)
    return float(mae_value)

class SimpleLLMCaller:
    def __init__(self, llm, max_tokens: int):
        self.llm = llm
        self.max_tokens = max_tokens

    def _format_prompt(self, stats_json: str) -> str:
        return (
        "You are an elite fantasy premier league football analytics model. "
        "Your task is to predict a player's fantasy 'total_points' for the **next match**, "
        "using ONLY the structured statistical features provided in JSON.\n\n"

        "### INSTRUCTIONS\n"
        "* Base your prediction STRICTLY on recent player form, minutes, rolling averages, and lag features.\n"
        "* Assume the player is available and healthy unless the stats themselves indicate otherwise "
        "   (e.g., repeated 0-minute matches → risk of non-start).\n"
        "* DO NOT use external football knowledge, team context, fame, or injuries not contained in the data.\n"
        "* Heavily weight:\n"
        "   - points_last_1, points_last_3, points_last_5 (recent form)\n"
        "   - played_last_1, starter_last_1, minutes_last_3 (likelihood to play)\n"
        "   - all *_mean_last_N features (rolling performance)\n"
        "* Produce a calibrated prediction — most players score 0–6 points, with occasional 10+.\n\n"

        "### OUTPUT FORMAT (MANDATORY)\n"
        "Respond **ONLY** with a valid JSON dictionary containing EXACTLY these two keys:\n"
        "  - \"predicted_total_points\": <number>\n"
        "  - \"rationale\": <short explanation string>\n\n"

        "NO markdown. NO code blocks. NO other text.\n\n"

        "### PLAYER DATA\n"
        f"{stats_json}\n"
    )

    def invoke(self, stats_json: str):
        prompt = self._format_prompt(stats_json)
        # The Dartmouth client accepts a plain string prompt
        return self.llm.invoke(prompt)

def build_llm_chain(llm_config: LlmConfig):
    chat_llm = ChatDartmouth(
    model_name=llm_config.model_name,
    temperature=llm_config.temperature,
    max_tokens=llm_config.max_output_tokens,
    )
    return SimpleLLMCaller(chat_llm, max_tokens=llm_config.max_output_tokens)

def _safe_float(value: object) -> Optional[float]:
    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        # remove ```python ``` blocks
        value = re.sub(r"```.*?```", "", value, flags=re.DOTALL)
        # try direct parse
        try:
            return float(value)
        except ValueError:
            # extract first number
            m = re.search(r"-?\d+(?:\.\d+)?", value)
            if m:
                try:
                    return float(m.group(0))
                except ValueError:
                    return None
    return None

def predict_points_with_llm(
    engine_chain,
    evaluation_df: pd.DataFrame,
    feature_columns: List[str],
    feature_config: FeatureConfig,
    llm_config: LlmConfig,
    fallback_value: Optional[float] = None,
    clamp_range: Optional[tuple[Optional[float], Optional[float]]] = (0.0, 40.0),
    max_retries: int = 3,
    retry_sleep_seconds: float = 0.6,
    debug_first_n: int = 5,
    ) -> pd.Series:
    """
    Returns a Series aligned to evaluation_df.index; never attempts float(None).
    """
    subset_df = evaluation_df.iloc[: llm_config.max_rows_to_score].copy()
    predicted_rationales: List[str] = []

    # Build inputs
    input_json_strings: List[str] = []
    for _, row in subset_df.iterrows():
        row_dict: Dict[str, Any] = {k: float(row[k]) if pd.notnull(row[k]) else 0.0 for k in feature_columns}
        row_dict["_player_name"] = str(row.get(feature_config.player_name_column, "unknown"))
        row_dict["_gameweek"] = int(row.get(feature_config.gameweek_column, -1)) if pd.notnull(row.get(feature_config.gameweek_column, np.nan)) else -1
        input_json_strings.append(pd.Series(row_dict).to_json())

    lo, hi = (None, None)
    if clamp_range is not None:
        lo, hi = clamp_range

    predicted_values: List[float] = []
    debug_payloads: List[tuple[str, str]] = []

    for row_json in input_json_strings:
        raw_text: str = ""
        parsed_value: Optional[float] = None
        rationale_text = ""

        # retry loop
        for attempt in range(max_retries):
            try:
                llm_out = engine_chain.invoke(row_json)
                raw_text = getattr(llm_out, "content", None) or str(llm_out)

                # Try JSON first
                rationale_text = ""
                try:
                    obj = json.loads(raw_text)
                    candidate = obj.get("predicted_total_points", obj.get("prediction"))
                    rationale_text = obj.get("rationale", "")
                except Exception:
                    candidate = raw_text
                    rationale_text = ""
                parsed_value = _coerce_and_clamp(candidate, lo, hi)
                if parsed_value is not None:
                    break
            except Exception as e:
                raw_text = f"[error: {e}]"
                time.sleep(retry_sleep_seconds * (attempt + 1))

        # Keep debug info for first N
        if len(debug_payloads) < debug_first_n:
            debug_payloads.append((row_json, raw_text))

        # If still None, use fallback
        if parsed_value is None:
            parsed_value = _coerce_and_clamp(fallback_value, lo, hi)

        predicted_values.append(float(parsed_value))
        predicted_rationales.append(rationale_text)

    #return pd.Series(predicted_values, index=subset_df.index, name="llm_pred_total_points")
    return pd.DataFrame({
    "llm_pred_total_points": predicted_values,
    "llm_rationale": predicted_rationales
}, index=subset_df.index)

def _coerce_and_clamp(value: object, lo: Optional[float], hi: Optional[float]) -> Optional[float]:
    v = _safe_float(value)
    if v is None:
        return None
    if lo is not None:
        v = max(v, float(lo))
    if hi is not None:
        v = min(v, float(hi))
    return float(v)

def main():
    # ---- 6.1 Load data
    data_frames = load_fantasy_data(
    merged_gw_path="data/merged_gw.csv",
    merged_seasons_path="data/cleaned_merged_seasons.csv"
    )
    merged_gw_df: pd.DataFrame = data_frames["merged_gw"]

    # ---- 6.2 Configure features
    feature_config = FeatureConfig(
    rolling_window_games=5,
    # Example: easily switch which features to use by editing this list.
    # Leave empty [] to include ALL engineered rolling features.
    selected_feature_columns=[
    # Examples (these must exist in your data after engineering):
    # "goals_scored_last_10_games",
    # "assists_last_10_games",
    # "minutes_last_10_games",
    # "xG_last_10_games",
    # "xA_last_10_games",
    # If unsure, leave this empty and let the code include all rolling features.
    ]
    )

    # ---- 6.3 Engineer rolling features
    engineered_df = compute_player_rolling_totals(merged_gw_df, feature_config)
    #print("Columns after feature engineering:", engineered_df.columns.tolist())

    # ---- 6.4 Build feature matrix X and target y
    feature_matrix, target_series, feature_columns = build_feature_matrix_and_target(
    engineered_df, feature_config
    )

    # Keep identifiers in the feature_matrix for LLM context
    feature_matrix[feature_config.player_name_column] = engineered_df[feature_config.player_name_column].values
    feature_matrix[feature_config.gameweek_column] = engineered_df[feature_config.gameweek_column].values

    print("Feature matrix shape:", feature_matrix.shape)
    #print("Feature columns used for ML:", feature_columns)

    baseline_mae = evaluate_linear_regression_baseline(
        feature_matrix.drop(columns=[feature_config.player_name_column, feature_config.gameweek_column], errors="ignore"),
        target_series
    )
    print(f"Baseline Linear Regression MAE: {baseline_mae:.4f}")

    # ---- 6.6 LLM configuration and chain
    llm_config = LlmConfig(
    model_name="meta.llama-3.2-11b-vision-instruct",
    temperature=0.0,
    max_output_tokens=128,
    max_rows_to_score=100 # adjust for cost/time
    )
    llm_chain = build_llm_chain(llm_config)

    # ---- 6.7 Score a subset with the LLM and evaluate
    # Align features the LLM will see (include player name and GW for context)
    llm_input_df = feature_matrix.copy()

    training_mean_points = float(target_series.mean())

    max_rows = llm_config.max_rows_to_score
    #feature_matrix = feature_matrix.iloc[:max_rows]
    #target_series = target_series.iloc[:max_rows]

    if len(feature_matrix) <= max_rows:
        sampled_df = feature_matrix.copy()
        sampled_targets = target_series.copy()
    else:
        sampled_indices = feature_matrix.sample(n=max_rows, random_state=42).index
        sampled_df = feature_matrix.loc[sampled_indices]
        sampled_targets = target_series.loc[sampled_indices]

    feature_matrix = sampled_df
    target_series = sampled_targets

    llm_chain = build_llm_chain(llm_config)

    batch_size = 50
    all_predictions = []

    for i in range(0, len(feature_matrix), batch_size):
        print(f"Scoring batch {i}–{i+batch_size}...")
        batch_df = feature_matrix.iloc[i:i+batch_size]
        batch_predictions = predict_points_with_llm(
            engine_chain=llm_chain,
            evaluation_df=batch_df,
            feature_columns=feature_columns,
            feature_config=feature_config,
            llm_config=llm_config,
            fallback_value=training_mean_points,
            clamp_range=(0.0, 40.0),
            debug_first_n=3,
        )
        all_predictions.append(batch_predictions)

    llm_predictions = pd.concat(all_predictions)

    # Align ground truth for the scored subset
    common_index = llm_predictions.index
    ground_truth_subset = target_series.loc[common_index]

    # Mask invalid predictions
    valid_mask = (
        llm_predictions["llm_pred_total_points"].notna() &
        np.isfinite(llm_predictions["llm_pred_total_points"])
    )
    valid_count = int(valid_mask.sum())
    print(f"LLM rows scored: {len(common_index)} | valid for MAE: {valid_count} | dropped: {len(common_index)-valid_count}")

    if valid_count > 0:
        llm_mae = mean_absolute_error(
            ground_truth_subset[valid_mask],
            llm_predictions.loc[valid_mask, "llm_pred_total_points"]
        )
        print(f"LLM MAE on valid rows: {llm_mae:.4f}")
    else:
        print("No valid LLM predictions. Skipping MAE.")

    # ---- 6.8 Inspect a few scored rows (data representation)
    preview_df = engineered_df.loc[common_index, [feature_config.player_name_column, feature_config.gameweek_column, feature_config.target_points_column]].copy()
    preview_df["llm_pred_total_points"] = llm_predictions["llm_pred_total_points"]
    # preview_df["llm_rationale"] = llm_predictions["llm_rationale"]
    print("\nPreview of scored rows:")
    print(preview_df.head(10).to_string(index=False))

if __name__ == "__main__":
    if not os.getenv("DARTMOUTH_CHAT_API_KEY"):
       raise RuntimeError("Please set DARTMOUTH_CHAT_API_KEY in your environment.")
    main()


